name = "EnergyModelsRecedingHorizon"
uuid = "37ec17de-8561-4b6b-83ee-0529988fea82"
authors = ["Lucas Ferreira Bernadino, Julian Straus, Halvor Aarnes Krog"]
version = "0.1.1"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
EnergyModelsBase = "5d7e687e-f956-46f3-9045-6f5a5fd49f50"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
TimeStruct = "f9ed5ce0-9f41-4eaa-96da-f38ab8df101c"

[weakdeps]
ParametricOptInterface = "0ce4ce61-57bf-432b-a095-efac525d185e"
EnergyModelsGeography = "3f775d88-a4da-46c4-a2cc-aa9f16db6708"

[extensions]
POIExt = "ParametricOptInterface"
EMGExt = "EnergyModelsGeography"
EMGPOIExt = ["EnergyModelsGeography", "ParametricOptInterface"]

[compat]
Accessors = "0.1.42"
CSV = "0.10.15"
DataFrames = "1.7.0"
EnergyModelsBase = "0.9.0"
EnergyModelsGeography = "0.11.0"
JuMP = "1.24"
ParametricOptInterface = "0.9"
TimeStruct = "0.9.1"
julia = "1.10"
